export const ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_ALREADY_USED: "EMAIL_ALREADY_USED",

  BATTLE_NOT_FOUND: "BATTLE_NOT_FOUND",
  BATTLE_INVALID_STATE: "BATTLE_INVALID_STATE",
  BATTLE_CODE_GENERATION_FAILED: "BATTLE_CODE_GENERATION_FAILED",
  CANNOT_JOIN_OWN_BATTLE: "CANNOT_JOIN_OWN_BATTLE",
  BATTLE_ALREADY_MATCHED: "BATTLE_ALREADY_MATCHED",
  ALREADY_SUBMITTED: "ALREADY_SUBMITTED",

  OCR_NO_BATTLE_CODE: "OCR_NO_BATTLE_CODE",
  OCR_NO_SCORE: "OCR_NO_SCORE",
  IMAGE_DUPLICATE: "IMAGE_DUPLICATE",

  STAMP_RATE_LIMIT: "STAMP_RATE_LIMIT",

  INTERNAL: "INTERNAL",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
